package com.kwe.kweplus.dao;

import com.kwe.kweplus.modal.JintieModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface JintieModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jintie_model
     *
     * @mbg.generated Wed Jun 26 14:31:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jintie_model
     *
     * @mbg.generated Wed Jun 26 14:31:33 CST 2019
     */
    int insert(JintieModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jintie_model
     *
     * @mbg.generated Wed Jun 26 14:31:33 CST 2019
     */
    JintieModel selectByPrimaryKey(Integer id);
    JintieModel selectByRemarks1(@Param("remark1") String remark1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jintie_model
     *
     * @mbg.generated Wed Jun 26 14:31:33 CST 2019
     */
    List<JintieModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jintie_model
     *
     * @mbg.generated Wed Jun 26 14:31:33 CST 2019
     */
    int updateByPrimaryKey(JintieModel record);

    int updateByRemarks1(JintieModel record);
}