package com.kwe.kweplus.modal;

import java.util.Date;

public class JintieModelList {

    private Integer id;

    // 客户ID GD 而不是C0000002
    private String custom_key;
    //模板名称
    private String model_id;
    //创建时间
    private Date create_time;
   //创建人
    private String create_user;
 //修改时间
    private Date update_time;
   //修改人
    private String update_user;
    
    private String remarks1;

    private String remarks2;

    private String remarks3;

    private String remarks4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model_list.remarks10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remarks10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.id
     *
     * @return the value of jintie_model_list.id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.id
     *
     * @param id the value for jintie_model_list.id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.custom_key
     *
     * @return the value of jintie_model_list.custom_key
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getCustom_key() {
        return custom_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.custom_key
     *
     * @param custom_key the value for jintie_model_list.custom_key
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setCustom_key(String custom_key) {
        this.custom_key = custom_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.model_id
     *
     * @return the value of jintie_model_list.model_id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getModel_id() {
        return model_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.model_id
     *
     * @param model_id the value for jintie_model_list.model_id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setModel_id(String model_id) {
        this.model_id = model_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.creat_time
     *
     * @return the value of jintie_model_list.creat_time
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.creat_time
     *
     * @param creat_time the value for jintie_model_list.creat_time
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setCreate_time(Date creat_time) {
        this.create_time = creat_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.creat_user
     *
     * @return the value of jintie_model_list.creat_user
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getCreate_user() {
        return create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.creat_user
     *
     * @param creat_user the value for jintie_model_list.creat_user
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setCreat_user(String creat_user) {
        this.create_user = creat_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.update_time
     *
     * @return the value of jintie_model_list.update_time
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.update_time
     *
     * @param update_time the value for jintie_model_list.update_time
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.update_user
     *
     * @return the value of jintie_model_list.update_user
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getUpdate_user() {
        return update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.update_user
     *
     * @param update_user the value for jintie_model_list.update_user
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setUpdate_user(String update_user) {
        this.update_user = update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks1
     *
     * @return the value of jintie_model_list.remarks1
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks1
     *
     * @param remarks1 the value for jintie_model_list.remarks1
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks2
     *
     * @return the value of jintie_model_list.remarks2
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks2
     *
     * @param remarks2 the value for jintie_model_list.remarks2
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks3
     *
     * @return the value of jintie_model_list.remarks3
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks3() {
        return remarks3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks3
     *
     * @param remarks3 the value for jintie_model_list.remarks3
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks3(String remarks3) {
        this.remarks3 = remarks3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks4
     *
     * @return the value of jintie_model_list.remarks4
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks4() {
        return remarks4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks4
     *
     * @param remarks4 the value for jintie_model_list.remarks4
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks4(String remarks4) {
        this.remarks4 = remarks4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks5
     *
     * @return the value of jintie_model_list.remarks5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks5() {
        return remarks5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks5
     *
     * @param remarks5 the value for jintie_model_list.remarks5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks5(String remarks5) {
        this.remarks5 = remarks5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks6
     *
     * @return the value of jintie_model_list.remarks6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks6() {
        return remarks6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks6
     *
     * @param remarks6 the value for jintie_model_list.remarks6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks6(String remarks6) {
        this.remarks6 = remarks6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks7
     *
     * @return the value of jintie_model_list.remarks7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks7() {
        return remarks7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks7
     *
     * @param remarks7 the value for jintie_model_list.remarks7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks7(String remarks7) {
        this.remarks7 = remarks7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks8
     *
     * @return the value of jintie_model_list.remarks8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks8() {
        return remarks8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks8
     *
     * @param remarks8 the value for jintie_model_list.remarks8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks8(String remarks8) {
        this.remarks8 = remarks8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks9
     *
     * @return the value of jintie_model_list.remarks9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks9() {
        return remarks9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks9
     *
     * @param remarks9 the value for jintie_model_list.remarks9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks9(String remarks9) {
        this.remarks9 = remarks9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model_list.remarks10
     *
     * @return the value of jintie_model_list.remarks10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemarks10() {
        return remarks10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model_list.remarks10
     *
     * @param remarks10 the value for jintie_model_list.remarks10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemarks10(String remarks10) {
        this.remarks10 = remarks10;
    }

    @Override
    public String toString() {
        return "JintieModelList{" +
                "id=" + id +
                ", custom_key='" + custom_key + '\'' +
                ", model_id='" + model_id + '\'' +
                ", creat_time=" + create_time +
                ", creat_user='" + create_user + '\'' +
                ", update_time=" + update_time +
                ", update_user=" + update_user +
                ", remarks1='" + remarks1 + '\'' +
                ", remarks2='" + remarks2 + '\'' +
                ", remarks3='" + remarks3 + '\'' +
                ", remarks4='" + remarks4 + '\'' +
                ", remarks5='" + remarks5 + '\'' +
                ", remarks6='" + remarks6 + '\'' +
                ", remarks7='" + remarks7 + '\'' +
                ", remarks8='" + remarks8 + '\'' +
                ", remarks9='" + remarks9 + '\'' +
                ", remarks10='" + remarks10 + '\'' +
                '}';
    }

}