package com.kwe.kweplus.modal;

public class JintieModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark1
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark2
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark3
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark4
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.remark10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String remark10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jintie_model.text
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.id
     *
     * @return the value of jintie_model.id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.id
     *
     * @param id the value for jintie_model.id
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark1
     *
     * @return the value of jintie_model.remark1
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark1
     *
     * @param remark1 the value for jintie_model.remark1
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark2
     *
     * @return the value of jintie_model.remark2
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark2
     *
     * @param remark2 the value for jintie_model.remark2
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark3
     *
     * @return the value of jintie_model.remark3
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark3
     *
     * @param remark3 the value for jintie_model.remark3
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark4
     *
     * @return the value of jintie_model.remark4
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark4() {
        return remark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark4
     *
     * @param remark4 the value for jintie_model.remark4
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark4(String remark4) {
        this.remark4 = remark4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark5
     *
     * @return the value of jintie_model.remark5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark5() {
        return remark5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark5
     *
     * @param remark5 the value for jintie_model.remark5
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark5(String remark5) {
        this.remark5 = remark5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark6
     *
     * @return the value of jintie_model.remark6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark6() {
        return remark6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark6
     *
     * @param remark6 the value for jintie_model.remark6
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark6(String remark6) {
        this.remark6 = remark6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark7
     *
     * @return the value of jintie_model.remark7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark7() {
        return remark7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark7
     *
     * @param remark7 the value for jintie_model.remark7
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark7(String remark7) {
        this.remark7 = remark7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark8
     *
     * @return the value of jintie_model.remark8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark8() {
        return remark8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark8
     *
     * @param remark8 the value for jintie_model.remark8
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark8(String remark8) {
        this.remark8 = remark8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark9
     *
     * @return the value of jintie_model.remark9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark9() {
        return remark9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark9
     *
     * @param remark9 the value for jintie_model.remark9
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark9(String remark9) {
        this.remark9 = remark9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.remark10
     *
     * @return the value of jintie_model.remark10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getRemark10() {
        return remark10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.remark10
     *
     * @param remark10 the value for jintie_model.remark10
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setRemark10(String remark10) {
        this.remark10 = remark10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jintie_model.text
     *
     * @return the value of jintie_model.text
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jintie_model.text
     *
     * @param text the value for jintie_model.text
     *
     * @mbg.generated Wed Jun 26 14:23:39 CST 2019
     */
    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return "JintieModel{" +
                "id=" + id +
                ", remark1='" + remark1 + '\'' +
                ", remark2='" + remark2 + '\'' +
                ", remark3='" + remark3 + '\'' +
                ", remark4='" + remark4 + '\'' +
                ", remark5='" + remark5 + '\'' +
                ", remark6='" + remark6 + '\'' +
                ", remark7='" + remark7 + '\'' +
                ", remark8='" + remark8 + '\'' +
                ", remark9='" + remark9 + '\'' +
                ", remark10='" + remark10 + '\'' +
                ", text='" + text + '\'' +
                '}';
    }
}